module.exports = {
  content: [
      "./resources/**/*.blade.php",
      "./resources/**/*.js",
      "./resources/**/*.vue",
  ],
    theme: {
        screens: {
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1140px',
        },
        colors: {
            "transparent": "transparent",
            "black": "#000000",
            "white": "#ffffff",
            "red": "#f44336",
            "red-50": "#ffebee",
            "red-100": "#ffcdd2",
            "red-200": "#ef9a9a",
            "red-300": "#e57373",
            "red-400": "#ef5350",
            "red-500": "#f44336",
            "red-600": "#e53935",
            "red-700": "#d32f2f",
            "red-800": "#c62828",
            "red-900": "#b71c1c",
            "red-100-accent": "#ff8a80",
            "red-200-accent": "#ff5252",
            "red-400-accent": "#ff1744",
            "red-700-accent": "#d50000",
            "pink": "#e91e63",
            "pink-50": "#fce4ec",
            "pink-100": "#f8bbd0",
            "pink-200": "#f48fb1",
            "pink-300": "#f06292",
            "pink-400": "#ec407a",
            "pink-500": "#e91e63",
            "pink-600": "#d81b60",
            "pink-700": "#c2185b",
            "pink-800": "#ad1457",
            "pink-900": "#880e4f",
            "pink-100-accent": "#ff80ab",
            "pink-200-accent": "#ff4081",
            "pink-400-accent": "#f50057",
            "pink-700-accent": "#c51162",
            "purple": "#9c27b0",
            "purple-50": "#f3e5f5",
            "purple-100": "#e1bee7",
            "purple-200": "#ce93d8",
            "purple-300": "#ba68c8",
            "purple-400": "#ab47bc",
            "purple-500": "#9c27b0",
            "purple-600": "#8e24aa",
            "purple-700": "#7b1fa2",
            "purple-800": "#6a1b9a",
            "purple-900": "#4a148c",
            "purple-100-accent": "#ea80fc",
            "purple-200-accent": "#e040fb",
            "purple-400-accent": "#d500f9",
            "purple-700-accent": "#aa00ff",
            "deep-purple": "#673ab7",
            "deep-purple-50": "#ede7f6",
            "deep-purple-100": "#d1c4e9",
            "deep-purple-200": "#b39ddb",
            "deep-purple-300": "#9575cd",
            "deep-purple-400": "#7e57c2",
            "deep-purple-500": "#673ab7",
            "deep-purple-600": "#5e35b1",
            "deep-purple-700": "#512da8",
            "deep-purple-800": "#4527a0",
            "deep-purple-900": "#311b92",
            "deep-purple-100-accent": "#b388ff",
            "deep-purple-200-accent": "#7c4dff",
            "deep-purple-400-accent": "#651fff",
            "deep-purple-700-accent": "#6200ea",
            "indigo": "#3f51b5",
            "indigo-50": "#e8eaf6",
            "indigo-100": "#c5cae9",
            "indigo-200": "#9fa8da",
            "indigo-300": "#7986cb",
            "indigo-400": "#5c6bc0",
            "indigo-500": "#3f51b5",
            "indigo-600": "#3949ab",
            "indigo-700": "#303f9f",
            "indigo-800": "#283593",
            "indigo-900": "#1a237e",
            "indigo-100-accent": "#8c9eff",
            "indigo-200-accent": "#536dfe",
            "indigo-400-accent": "#3d5afe",
            "indigo-700-accent": "#304ffe",
            "blue": "#2196f3",
            "blue-50": "#e3f2fd",
            "blue-100": "#bbdefb",
            "blue-200": "#90caf9",
            "blue-300": "#64b5f6",
            "blue-400": "#42a5f5",
            "blue-500": "#2196f3",
            "blue-600": "#1e88e5",
            "blue-700": "#1976d2",
            "blue-800": "#1565c0",
            "blue-900": "#0d47a1",
            "blue-100-accent": "#82b1ff",
            "blue-200-accent": "#448aff",
            "blue-400-accent": "#2979ff",
            "blue-700-accent": "#2962ff",
            "light-blue": "#03a9f4",
            "light-blue-50": "#e1f5fe",
            "light-blue-100": "#b3e5fc",
            "light-blue-200": "#81d4fa",
            "light-blue-300": "#4fc3f7",
            "light-blue-400": "#29b6f6",
            "light-blue-500": "#03a9f4",
            "light-blue-600": "#039be5",
            "light-blue-700": "#0288d1",
            "light-blue-800": "#0277bd",
            "light-blue-900": "#01579b",
            "light-blue-100-accent": "#80d8ff",
            "light-blue-200-accent": "#40c4ff",
            "light-blue-400-accent": "#00b0ff",
            "light-blue-700-accent": "#0091ea",
            "cyan": "#00bcd4",
            "cyan-50": "#e0f7fa",
            "cyan-100": "#b2ebf2",
            "cyan-200": "#80deea",
            "cyan-300": "#4dd0e1",
            "cyan-400": "#26c6da",
            "cyan-500": "#00bcd4",
            "cyan-600": "#00acc1",
            "cyan-700": "#0097a7",
            "cyan-800": "#00838f",
            "cyan-900": "#006064",
            "cyan-100-accent": "#84ffff",
            "cyan-200-accent": "#18ffff",
            "cyan-400-accent": "#00e5ff",
            "cyan-700-accent": "#00b8d4",
            "teal": "#009688",
            "teal-50": "#e0f2f1",
            "teal-100": "#b2dfdb",
            "teal-200": "#80cbc4",
            "teal-300": "#4db6ac",
            "teal-400": "#26a69a",
            "teal-500": "#009688",
            "teal-600": "#00897b",
            "teal-700": "#00796b",
            "teal-800": "#00695c",
            "teal-900": "#004d40",
            "teal-100-accent": "#a7ffeb",
            "teal-200-accent": "#64ffda",
            "teal-400-accent": "#1de9b6",
            "teal-700-accent": "#00bfa5",
            "green": "#4caf50",
            "green-50": "#e8f5e9",
            "green-100": "#c8e6c9",
            "green-200": "#a5d6a7",
            "green-300": "#81c784",
            "green-400": "#66bb6a",
            "green-500": "#4caf50",
            "green-600": "#43a047",
            "green-700": "#388e3c",
            "green-800": "#2e7d32",
            "green-900": "#1b5e20",
            "green-100-accent": "#b9f6ca",
            "green-200-accent": "#69f0ae",
            "green-400-accent": "#00e676",
            "green-700-accent": "#00c853",
            "light-green": "#8bc34a",
            "light-green-50": "#f1f8e9",
            "light-green-100": "#dcedc8",
            "light-green-200": "#c5e1a5",
            "light-green-300": "#aed581",
            "light-green-400": "#9ccc65",
            "light-green-500": "#8bc34a",
            "light-green-600": "#7cb342",
            "light-green-700": "#689f38",
            "light-green-800": "#558b2f",
            "light-green-900": "#33691e",
            "light-green-100-accent": "#ccff90",
            "light-green-200-accent": "#b2ff59",
            "light-green-400-accent": "#76ff03",
            "light-green-700-accent": "#64dd17",
            "lime": "#cddc39",
            "lime-50": "#f9fbe7",
            "lime-100": "#f0f4c3",
            "lime-200": "#e6ee9c",
            "lime-300": "#dce775",
            "lime-400": "#d4e157",
            "lime-500": "#cddc39",
            "lime-600": "#c0ca33",
            "lime-700": "#afb42b",
            "lime-800": "#9e9d24",
            "lime-900": "#827717",
            "lime-100-accent": "#f4ff81",
            "lime-200-accent": "#eeff41",
            "lime-400-accent": "#c6ff00",
            "lime-700-accent": "#aeea00",
            "yellow": "#ffeb3b",
            "yellow-50": "#fffde7",
            "yellow-100": "#fff9c4",
            "yellow-200": "#fff59d",
            "yellow-300": "#fff176",
            "yellow-400": "#ffee58",
            "yellow-500": "#ffeb3b",
            "yellow-600": "#fdd835",
            "yellow-700": "#fbc02d",
            "yellow-800": "#f9a825",
            "yellow-900": "#f57f17",
            "yellow-100-accent": "#ffff8d",
            "yellow-200-accent": "#ffff00",
            "yellow-400-accent": "#ffea00",
            "yellow-700-accent": "#ffd600",
            "amber": "#ffc107",
            "amber-50": "#fff8e1",
            "amber-100": "#ffecb3",
            "amber-200": "#ffe082",
            "amber-300": "#ffd54f",
            "amber-400": "#ffca28",
            "amber-500": "#ffc107",
            "amber-600": "#ffb300",
            "amber-700": "#ffa000",
            "amber-800": "#ff8f00",
            "amber-900": "#ff6f00",
            "amber-100-accent": "#ffe57f",
            "amber-200-accent": "#ffd740",
            "amber-400-accent": "#ffc400",
            "amber-700-accent": "#ffab00",
            "orange": "#ff9800",
            "orange-50": "#fff3e0",
            "orange-100": "#ffe0b2",
            "orange-200": "#ffcc80",
            "orange-300": "#ffb74d",
            "orange-400": "#ffa726",
            "orange-500": "#ff9800",
            "orange-600": "#fb8c00",
            "orange-700": "#f57c00",
            "orange-800": "#ef6c00",
            "orange-900": "#e65100",
            "orange-100-accent": "#ffd180",
            "orange-200-accent": "#ffab40",
            "orange-400-accent": "#ff9100",
            "orange-700-accent": "#ff6d00",
            "deep-orange": "#ff5722",
            "deep-orange-50": "#fbe9e7",
            "deep-orange-100": "#ffccbc",
            "deep-orange-200": "#ffab91",
            "deep-orange-300": "#ff8a65",
            "deep-orange-400": "#ff7043",
            "deep-orange-500": "#ff5722",
            "deep-orange-600": "#f4511e",
            "deep-orange-700": "#e64a19",
            "deep-orange-800": "#d84315",
            "deep-orange-900": "#bf360c",
            "deep-orange-100-accent": "#ff9e80",
            "deep-orange-200-accent": "#ff6e40",
            "deep-orange-400-accent": "#ff3d00",
            "deep-orange-700-accent": "#dd2c00",
            "brown": "#795548",
            "brown-50": "#efebe9",
            "brown-100": "#d7ccc8",
            "brown-200": "#bcaaa4",
            "brown-300": "#a1887f",
            "brown-400": "#8d6e63",
            "brown-500": "#795548",
            "brown-600": "#6d4c41",
            "brown-700": "#5d4037",
            "brown-800": "#4e342e",
            "brown-900": "#3e2723",
            "grey": "#9e9e9e",
            "grey-50": "#fafafa",
            "grey-100": "#f5f5f5",
            "grey-200": "#eeeeee",
            "grey-300": "#e0e0e0",
            "grey-400": "#bdbdbd",
            "grey-500": "#9e9e9e",
            "grey-600": "#757575",
            "grey-700": "#616161",
            "grey-800": "#424242",
            "grey-900": "#212121",
            "blue-grey": "#607d8b",
            "blue-grey-50": "#eceff1",
            "blue-grey-100": "#cfd8dc",
            "blue-grey-200": "#b0bec5",
            "blue-grey-300": "#90a4ae",
            "blue-grey-400": "#78909c",
            "blue-grey-500": "#607d8b",
            "blue-grey-600": "#546e7a",
            "blue-grey-700": "#455a64",
            "blue-grey-800": "#37474f",
            "blue-grey-900": "#263238",
            "red-contrast": "white",
            "red-50-contrast": "black",
            "red-100-contrast": "black",
            "red-200-contrast": "black",
            "red-300-contrast": "black",
            "red-400-contrast": "black",
            "red-500-contrast": "white",
            "red-600-contrast": "white",
            "red-700-contrast": "white",
            "red-800-contrast": "white",
            "red-900-contrast": "white",
            "red-100-accent-contrast": "black",
            "red-200-accent-contrast": "white",
            "red-400-accent-contrast": "white",
            "red-700-accent-contrast": "white",
            "pink-contrast": "white",
            "pink-50-contrast": "black",
            "pink-100-contrast": "black",
            "pink-200-contrast": "black",
            "pink-300-contrast": "black",
            "pink-400-contrast": "black",
            "pink-500-contrast": "white",
            "pink-600-contrast": "white",
            "pink-700-contrast": "white",
            "pink-800-contrast": "white",
            "pink-900-contrast": "white",
            "pink-100-accent-contrast": "black",
            "pink-200-accent-contrast": "white",
            "pink-400-accent-contrast": "white",
            "pink-700-accent-contrast": "white",
            "purple-contrast": "white",
            "purple-50-contrast": "black",
            "purple-100-contrast": "black",
            "purple-200-contrast": "black",
            "purple-300-contrast": "white",
            "purple-400-contrast": "white",
            "purple-500-contrast": "white",
            "purple-600-contrast": "white",
            "purple-700-contrast": "white",
            "purple-800-contrast": "white",
            "purple-900-contrast": "white",
            "purple-100-accent-contrast": "black",
            "purple-200-accent-contrast": "white",
            "purple-400-accent-contrast": "white",
            "purple-700-accent-contrast": "white",
            "deep-purple-contrast": "white",
            "deep-purple-50-contrast": "black",
            "deep-purple-100-contrast": "black",
            "deep-purple-200-contrast": "black",
            "deep-purple-300-contrast": "white",
            "deep-purple-400-contrast": "white",
            "deep-purple-500-contrast": "white",
            "deep-purple-600-contrast": "white",
            "deep-purple-700-contrast": "white",
            "deep-purple-800-contrast": "white",
            "deep-purple-900-contrast": "white",
            "deep-purple-100-accent-contrast": "black",
            "deep-purple-200-accent-contrast": "white",
            "deep-purple-400-accent-contrast": "white",
            "deep-purple-700-accent-contrast": "white",
            "indigo-contrast": "white",
            "indigo-50-contrast": "black",
            "indigo-100-contrast": "black",
            "indigo-200-contrast": "black",
            "indigo-300-contrast": "white",
            "indigo-400-contrast": "white",
            "indigo-500-contrast": "white",
            "indigo-600-contrast": "white",
            "indigo-700-contrast": "white",
            "indigo-800-contrast": "white",
            "indigo-900-contrast": "white",
            "indigo-100-accent-contrast": "black",
            "indigo-200-accent-contrast": "white",
            "indigo-400-accent-contrast": "white",
            "indigo-700-accent-contrast": "white",
            "blue-contrast": "white",
            "blue-50-contrast": "black",
            "blue-100-contrast": "black",
            "blue-200-contrast": "black",
            "blue-300-contrast": "black",
            "blue-400-contrast": "black",
            "blue-500-contrast": "white",
            "blue-600-contrast": "white",
            "blue-700-contrast": "white",
            "blue-800-contrast": "white",
            "blue-900-contrast": "white",
            "blue-100-accent-contrast": "black",
            "blue-200-accent-contrast": "white",
            "blue-400-accent-contrast": "white",
            "blue-700-accent-contrast": "white",
            "light-blue-contrast": "white",
            "light-blue-50-contrast": "black",
            "light-blue-100-contrast": "black",
            "light-blue-200-contrast": "black",
            "light-blue-300-contrast": "black",
            "light-blue-400-contrast": "black",
            "light-blue-500-contrast": "white",
            "light-blue-600-contrast": "white",
            "light-blue-700-contrast": "white",
            "light-blue-800-contrast": "white",
            "light-blue-900-contrast": "white",
            "light-blue-100-accent-contrast": "black",
            "light-blue-200-accent-contrast": "black",
            "light-blue-400-accent-contrast": "black",
            "light-blue-700-accent-contrast": "white",
            "cyan-contrast": "white",
            "cyan-50-contrast": "black",
            "cyan-100-contrast": "black",
            "cyan-200-contrast": "black",
            "cyan-300-contrast": "black",
            "cyan-400-contrast": "black",
            "cyan-500-contrast": "white",
            "cyan-600-contrast": "white",
            "cyan-700-contrast": "white",
            "cyan-800-contrast": "white",
            "cyan-900-contrast": "white",
            "cyan-100-accent-contrast": "black",
            "cyan-200-accent-contrast": "black",
            "cyan-400-accent-contrast": "black",
            "cyan-700-accent-contrast": "black",
            "teal-contrast": "white",
            "teal-50-contrast": "black",
            "teal-100-contrast": "black",
            "teal-200-contrast": "black",
            "teal-300-contrast": "black",
            "teal-400-contrast": "black",
            "teal-500-contrast": "white",
            "teal-600-contrast": "white",
            "teal-700-contrast": "white",
            "teal-800-contrast": "white",
            "teal-900-contrast": "white",
            "teal-100-accent-contrast": "black",
            "teal-200-accent-contrast": "black",
            "teal-400-accent-contrast": "black",
            "teal-700-accent-contrast": "black",
            "green-contrast": "white",
            "green-50-contrast": "black",
            "green-100-contrast": "black",
            "green-200-contrast": "black",
            "green-300-contrast": "black",
            "green-400-contrast": "black",
            "green-500-contrast": "white",
            "green-600-contrast": "white",
            "green-700-contrast": "white",
            "green-800-contrast": "white",
            "green-900-contrast": "white",
            "green-100-accent-contrast": "black",
            "green-200-accent-contrast": "black",
            "green-400-accent-contrast": "black",
            "green-700-accent-contrast": "black",
            "light-green-contrast": "black",
            "light-green-50-contrast": "black",
            "light-green-100-contrast": "black",
            "light-green-200-contrast": "black",
            "light-green-300-contrast": "black",
            "light-green-400-contrast": "black",
            "light-green-500-contrast": "black",
            "light-green-600-contrast": "black",
            "light-green-700-contrast": "black",
            "light-green-800-contrast": "white",
            "light-green-900-contrast": "white",
            "light-green-100-accent-contrast": "black",
            "light-green-200-accent-contrast": "black",
            "light-green-400-accent-contrast": "black",
            "light-green-700-accent-contrast": "black",
            "lime-contrast": "black",
            "lime-50-contrast": "black",
            "lime-100-contrast": "black",
            "lime-200-contrast": "black",
            "lime-300-contrast": "black",
            "lime-400-contrast": "black",
            "lime-500-contrast": "black",
            "lime-600-contrast": "black",
            "lime-700-contrast": "black",
            "lime-800-contrast": "black",
            "lime-900-contrast": "white",
            "lime-100-accent-contrast": "black",
            "lime-200-accent-contrast": "black",
            "lime-400-accent-contrast": "black",
            "lime-700-accent-contrast": "black",
            "yellow-contrast": "black",
            "yellow-50-contrast": "black",
            "yellow-100-contrast": "black",
            "yellow-200-contrast": "black",
            "yellow-300-contrast": "black",
            "yellow-400-contrast": "black",
            "yellow-500-contrast": "black",
            "yellow-600-contrast": "black",
            "yellow-700-contrast": "black",
            "yellow-800-contrast": "black",
            "yellow-900-contrast": "black",
            "yellow-100-accent-contrast": "black",
            "yellow-200-accent-contrast": "black",
            "yellow-400-accent-contrast": "black",
            "yellow-700-accent-contrast": "black",
            "amber-contrast": "black",
            "amber-50-contrast": "black",
            "amber-100-contrast": "black",
            "amber-200-contrast": "black",
            "amber-300-contrast": "black",
            "amber-400-contrast": "black",
            "amber-500-contrast": "black",
            "amber-600-contrast": "black",
            "amber-700-contrast": "black",
            "amber-800-contrast": "black",
            "amber-900-contrast": "black",
            "amber-100-accent-contrast": "black",
            "amber-200-accent-contrast": "black",
            "amber-400-accent-contrast": "black",
            "amber-700-accent-contrast": "black",
            "orange-contrast": "black",
            "orange-50-contrast": "black",
            "orange-100-contrast": "black",
            "orange-200-contrast": "black",
            "orange-300-contrast": "black",
            "orange-400-contrast": "black",
            "orange-500-contrast": "black",
            "orange-600-contrast": "black",
            "orange-700-contrast": "black",
            "orange-800-contrast": "white",
            "orange-900-contrast": "white",
            "orange-100-accent-contrast": "black",
            "orange-200-accent-contrast": "black",
            "orange-400-accent-contrast": "black",
            "orange-700-accent-contrast": "black",
            "deep-orange-contrast": "white",
            "deep-orange-50-contrast": "black",
            "deep-orange-100-contrast": "black",
            "deep-orange-200-contrast": "black",
            "deep-orange-300-contrast": "black",
            "deep-orange-400-contrast": "black",
            "deep-orange-500-contrast": "white",
            "deep-orange-600-contrast": "white",
            "deep-orange-700-contrast": "white",
            "deep-orange-800-contrast": "white",
            "deep-orange-900-contrast": "white",
            "deep-orange-100-accent-contrast": "black",
            "deep-orange-200-accent-contrast": "black",
            "deep-orange-400-accent-contrast": "white",
            "deep-orange-700-accent-contrast": "white",
            "brown-contrast": "white",
            "brown-50-contrast": "black",
            "brown-100-contrast": "black",
            "brown-200-contrast": "black",
            "brown-300-contrast": "white",
            "brown-400-contrast": "white",
            "brown-500-contrast": "white",
            "brown-600-contrast": "white",
            "brown-700-contrast": "white",
            "brown-800-contrast": "white",
            "brown-900-contrast": "white",
            "grey-contrast": "black",
            "grey-50-contrast": "black",
            "grey-100-contrast": "black",
            "grey-200-contrast": "black",
            "grey-300-contrast": "black",
            "grey-400-contrast": "black",
            "grey-500-contrast": "black",
            "grey-600-contrast": "white",
            "grey-700-contrast": "white",
            "grey-800-contrast": "white",
            "grey-900-contrast": "white",
            "blue-grey-contrast": "white",
            "blue-grey-50-contrast": "black",
            "blue-grey-100-contrast": "black",
            "blue-grey-200-contrast": "black",
            "blue-grey-300-contrast": "black",
            "blue-grey-400-contrast": "white",
            "blue-grey-500-contrast": "white",
            "blue-grey-600-contrast": "white",
            "blue-grey-700-contrast": "white",
            "blue-grey-800-contrast": "white",
            "blue-grey-900-contrast": "white"
            /*current: 'currentColor',
            transparent: 'transparent',

            black: '#000',
            white: '#fff',

            gray: {
                50: '#f9fafb',
                100: '#f3f4f6',
                200: '#e5e7eb',
                300: '#d1d5db',
                400: '#9ca3af',
                500: '#6b7280',
                600: '#4b5563',
                700: '#374151',
                800: '#1f2937',
                900: '#111827',
            },
            red: {
                50: '#fef2f2',
                100: '#fee2e2',
                200: '#fecaca',
                300: '#fca5a5',
                400: '#f87171',
                500: '#ef4444',
                600: '#dc2626',
                700: '#b91c1c',
                800: '#991b1b',
                900: '#7f1d1d',
            },
            yellow: {
                50: '#fffbeb',
                100: '#fef3c7',
                200: '#fde68a',
                300: '#fcd34d',
                400: '#fbbf24',
                500: '#f59e0b',
                600: '#d97706',
                700: '#b45309',
                800: '#92400e',
                900: '#78350f',
            },
            green: {
                50: '#ecfdf5',
                100: '#d1fae5',
                200: '#a7f3d0',
                300: '#6ee7b7',
                400: '#34d399',
                500: '#10b981',
                600: '#059669',
                700: '#047857',
                800: '#065f46',
                900: '#064e3b',
            },
            blue: {
                50: '#eff6ff',
                100: '#dbeafe',
                200: '#bfdbfe',
                300: '#93c5fd',
                400: '#60a5fa',
                500: '#3b82f6',
                600: '#2563eb',
                700: '#1d4ed8',
                800: '#1e40af',
                900: '#1e3a8a',
            },
            indigo: {
                50: '#eef2ff',
                100: '#e0e7ff',
                200: '#c3dafe',
                300: '#a5b4fc',
                400: '#818cf8',
                500: '#6366f1',
                600: '#4f46e5',
                700: '#4338ca',
                800: '#3730a3',
                900: '#312e81',
            },
            purple: {
                50: '#f5f3ff',
                100: '#ede9fe',
                200: '#ddd6fe',
                300: '#c4b5fd',
                400: '#a78bfa',
                500: '#8b5cf6',
                600: '#7c3aed',
                700: '#6d28d9',
                800: '#5b21b6',
                900: '#4c1d95',
            },
            pink: {
                50: '#fdf2f8',
                100: '#fce7f3',
                200: '#fbcfe8',
                300: '#f9a8d4',
                400: '#f472b6',
                500: '#ec4899',
                600: '#db2777',
                700: '#be185d',
                800: '#9d174d',
                900: '#831843',
            },
            lime: {
                50: '#F7FEE7',
                100: '#ECFCCB',
                200: '#D9F99D',
                300: '#BEF264',
                400: '#A3E635',
                500: '#84CC16',
                600: '#65A30D',
                700: '#4D7C0F',
                800: '#3F6212',
                900: '#365314',
            },*/
        },
        spacing: {
            px: '1px',
            px: '1px',
            '0': '0px',
            '0.5': '0.125rem',
            '1': '0.25rem',
            '1.5': '0.375rem',
            '2': '0.5rem',
            '2.5': '0.625rem',
            '3': '0.75rem',
            '3.5': '0.875rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '7': '1.75rem',
            '8': '2rem',
            '9': '2.25rem',
            '10': '2.5rem',
            '11': '2.75rem',
            '12': '3rem',
            '14': '3.5rem',
            '16': '4rem',
            '20': '5rem',
            '24': '6rem',
            '32': '8rem',
            '36': '9rem',
            '40': '10rem',
            '44': '11rem',
            '48': '12rem',
            '52': '13rem',
            '56': '14rem',
            '60': '15rem',
            '64': '16rem',
            '72': '18rem',
            '80': '20rem',
            '96': '24rem',
            '128': '32rem',
            '160': '40rem',
            '192': '48rem',
        },
        backgroundColor: theme => ({
            ...theme('colors'),
            body: '#0098C8',
        }),
        backgroundPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
        },
        backgroundSize: {
            auto: 'auto',
            cover: 'cover',
            contain: 'contain',
        },
        borderColor: theme => ({
            ...theme('colors'),
            DEFAULT: '#e5e7eb',
        }),
        borderRadius: {
            none: '0',
            sm: '0.125rem',
            DEFAULT: '6px',
            lg: '0.5rem',
            xl: '0.75rem',
            '2xl': '1rem',
            '3xl': '1.5rem',
            '4xl': '2rem',
            '6xl': '3rem',
            '12xl': '6rem',
            full: '9999px',
        },
        borderWidth: {
            DEFAULT: '1px',
            '0': '0',
            '2': '2px',
            '4': '4px',
            '8': '8px',
        },
        boxShadow: {
            sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
            DEFAULT: '0px 1px 2px rgba(148, 163, 184, 0.35), 0px 6px 6px rgba(203, 213, 225, 0.15)',
            md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
            lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
            xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
            '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
            inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
            none: 'none',
        },
        container: {},
        cursor: {
            auto: 'auto',
            DEFAULT: 'default',
            pointer: 'pointer',
            wait: 'wait',
            text: 'text',
            move: 'move',
            'not-allowed': 'not-allowed',
        },
        fill: {
            current: 'currentColor',
        },
        flex: {
            '1': '1 1 0%',
            auto: '1 1 auto',
            initial: '0 1 auto',
            none: 'none',
        },
        flexGrow: {
            '0': '0',
            DEFAULT: '1',
        },
        flexShrink: {
            '0': '0',
            DEFAULT: '1',
        },
        fontFamily: {
            body: '"DM Sans", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
            heading: '"DM Sans", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
            sans: '"DM Sans", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
            serif: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
            mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        },
        fontSize: {
            xs: '0.75rem',
            sm: '0.875rem',
            base: '1rem',
            lg: '1.125rem',
            xl: '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '3.75rem',
            '7xl': '4.5rem',
            '8xl': '6rem',
            '9xl': '8rem'
        },
        fontWeight: {
            hairline: '100',
            thin: '200',
            light: '300',
            normal: '400',
            medium: '500',
            semibold: '600',
            bold: '700',
            extrabold: '800',
            black: '900',
        },
        height: theme => ({
            auto: 'auto',
            ...theme('spacing'),
            full: '100%',
            screen: '100vh',
        }),
        inset: {
            '0': '0',
            auto: 'auto',
            '1/2': '50%',
        },
        letterSpacing: {
            tighter: '-0.05em',
            tight: '-0.025em',
            normal: '0',
            wide: '0.025em',
            wider: '0.05em',
            widest: '0.1em',
        },
        lineHeight: {
            none: '1',
            tight: '1.25',
            snug: '1.375',
            normal: '1.5',
            relaxed: '1.625',
            loose: '2',
        },
        listStyleType: {
            none: 'none',
            disc: 'disc',
            decimal: 'decimal',
        },
        margin: (theme, { negative }) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
            'for-radius': '5.4rem',
        }),
        maxHeight: {
            full: '100%',
            screen: '100vh',
        },
        maxWidth: {
            none: 'none',
            xs: '20rem',
            sm: '24rem',
            md: '28rem',
            lg: '32rem',
            xl: '36rem',
            '2xl': '42rem',
            '3xl': '48rem',
            '4xl': '56rem',
            '5xl': '64rem',
            '6xl': '72rem',
            '7xl': '80rem',
            full: '100%',
            min: 'min-content',
            max: 'max-content',
            prose: '65ch',
        },
        minHeight: {
            '0': '0',
            full: '100%',
            screen: '100vh',
        },
        minWidth: {
            '0': '0',
            full: '100%',
        },
        objectPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
        },
        opacity: {
            '0': '0',
            '5': '0.05',
            '10': '0.1',
            '20': '0.2',
            '25': '0.25',
            '30': '0.3',
            '40': '0.4',
            '50': '0.5',
            '60': '0.6',
            '70': '0.7',
            '75': '0.75',
            '80': '0.8',
            '90': '0.9',
            '95': '0.95',
            '100': '1',
        },
        order: {
            first: '-9999',
            last: '9999',
            none: '0',
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
            '6': '6',
            '7': '7',
            '8': '8',
            '9': '9',
            '10': '10',
            '11': '11',
            '12': '12',
        },
        padding: theme => theme('spacing'),
        placeholderColor: theme => theme('colors'),
        stroke: {
            current: 'currentColor',
        },
        textColor: theme => ({
            ...theme('colors'),
            body: '#111827',
        }),
        width: theme => ({
            auto: 'auto',
            ...theme('spacing'),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            '1/12': '8.333333%',
            '2/12': '16.666667%',
            '3/12': '25%',
            '4/12': '33.333333%',
            '5/12': '41.666667%',
            '6/12': '50%',
            '7/12': '58.333333%',
            '8/12': '66.666667%',
            '9/12': '75%',
            '10/12': '83.333333%',
            '11/12': '91.666667%',
            full: '100%',
            screen: '100vw',
        }),
        zIndex: {
            auto: 'auto',
            '0': '0',
            '10': '10',
            '20': '20',
            '30': '30',
            '40': '40',
            '50': '50',
        },
    },
    variants: {
        accessibility: ['responsive', 'focus-within', 'focus'],
        alignContent: ['responsive'],
        alignItems: ['responsive'],
        alignSelf: ['responsive'],
        animation: ['responsive'],
        appearance: ['responsive'],
        backgroundAttachment: ['responsive'],
        backgroundClip: ['responsive'],
        backgroundColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
        backgroundImage: ['responsive'],
        backgroundOpacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        backgroundPosition: ['responsive'],
        backgroundRepeat: ['responsive'],
        backgroundSize: ['responsive'],
        borderCollapse: ['responsive'],
        borderColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
        borderOpacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        borderRadius: ['responsive'],
        borderStyle: ['responsive'],
        borderWidth: ['responsive'],
        boxShadow: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        boxSizing: ['responsive'],
        clear: ['responsive'],
        container: ['responsive'],
        cursor: ['responsive'],
        display: ['responsive'],
        divideColor: ['responsive', 'dark'],
        divideOpacity: ['responsive'],
        divideStyle: ['responsive'],
        divideWidth: ['responsive'],
        fill: ['responsive'],
        flex: ['responsive'],
        flexDirection: ['responsive'],
        flexGrow: ['responsive'],
        flexShrink: ['responsive'],
        flexWrap: ['responsive'],
        float: ['responsive'],
        fontFamily: ['responsive'],
        fontSize: ['responsive'],
        fontSmoothing: ['responsive'],
        fontStyle: ['responsive'],
        fontVariantNumeric: ['responsive'],
        fontWeight: ['responsive'],
        gap: ['responsive'],
        gradientColorStops: ['responsive', 'dark', 'hover', 'focus'],
        gridAutoColumns: ['responsive'],
        gridAutoFlow: ['responsive'],
        gridAutoRows: ['responsive'],
        gridColumn: ['responsive'],
        gridColumnEnd: ['responsive'],
        gridColumnStart: ['responsive'],
        gridRow: ['responsive'],
        gridRowEnd: ['responsive'],
        gridRowStart: ['responsive'],
        gridTemplateColumns: ['responsive'],
        gridTemplateRows: ['responsive'],
        height: ['responsive'],
        inset: ['responsive'],
        justifyContent: ['responsive'],
        justifyItems: ['responsive'],
        justifySelf: ['responsive'],
        letterSpacing: ['responsive'],
        lineHeight: ['responsive'],
        listStylePosition: ['responsive'],
        listStyleType: ['responsive'],
        margin: ['responsive'],
        maxHeight: ['responsive'],
        maxWidth: ['responsive'],
        minHeight: ['responsive'],
        minWidth: ['responsive'],
        objectFit: ['responsive'],
        objectPosition: ['responsive'],
        opacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        order: ['responsive'],
        outline: ['responsive', 'focus-within', 'focus'],
        overflow: ['responsive'],
        overscrollBehavior: ['responsive'],
        padding: ['responsive'],
        placeContent: ['responsive'],
        placeItems: ['responsive'],
        placeSelf: ['responsive'],
        placeholderColor: ['responsive', 'dark', 'focus'],
        placeholderOpacity: ['responsive', 'focus'],
        pointerEvents: ['responsive'],
        position: ['responsive'],
        resize: ['responsive'],
        ringColor: ['responsive', 'dark', 'focus-within', 'focus'],
        ringOffsetColor: ['responsive', 'dark', 'focus-within', 'focus'],
        ringOffsetWidth: ['responsive', 'focus-within', 'focus'],
        ringOpacity: ['responsive', 'focus-within', 'focus'],
        ringWidth: ['responsive', 'focus-within', 'focus'],
        rotate: ['responsive', 'hover', 'focus'],
        scale: ['responsive', 'hover', 'focus'],
        skew: ['responsive', 'hover', 'focus'],
        space: ['responsive'],
        stroke: ['responsive'],
        strokeWidth: ['responsive'],
        tableLayout: ['responsive'],
        textAlign: ['responsive'],
        textColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
        textDecoration: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        textOpacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        textOverflow: ['responsive'],
        textTransform: ['responsive'],
        transform: ['responsive'],
        transformOrigin: ['responsive'],
        transitionDelay: ['responsive'],
        transitionDuration: ['responsive'],
        transitionProperty: ['responsive'],
        transitionTimingFunction: ['responsive'],
        translate: ['responsive', 'hover', 'focus'],
        userSelect: ['responsive'],
        verticalAlign: ['responsive'],
        visibility: ['responsive'],
        whitespace: ['responsive'],
        width: ['responsive'],
        wordBreak: ['responsive'],
        zIndex: ['responsive', 'focus-within', 'focus'],
    },
  plugins: [],
}
